# Generated by Django 2.2.6 on 2023-07-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('number_of_times_visited', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('availability_during_week', models.CharField(max_length=255)),
                ('number_of_times_visited', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank='True', upload_to='sites/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=9)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_activity_set', to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('meal_name', models.CharField(max_length=255)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=9)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='sites.Eatery')),
            ],
        ),
        migrations.CreateModel(
            name='EateryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, upload_to='eateries/')),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.Eatery')),
            ],
        ),
        migrations.AddField(
            model_name='eatery',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eateries_set', to='sites.Site'),
        ),
    ]
